- name: tag AMI images
  amazon.aws.ec2_tag:
    region: "{{ item.key }}"
    resource: "{{ item.value }}"
    state: present
    tags:
      Name: "{{ new_ami_name | default('no name specified') }}"
      ansiblecloud: "{{ new_tag | default('') }}"
  loop: "{{ ami_list | dict2items }}"

- name: give persmissions for AMI to be launched by specified account
  amazon.aws.ec2_ami:
    region: "{{ item.key }}"
    image_id: "{{ item.value }}"
    state: present
    purge_tags: false
    launch_permissions:
      user_ids: "{{ user_id_list }}"
  loop: "{{ ami_list | dict2items }}"
