- name: debug test
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: print out each ami from a dictionary
      debug:
        msg: "{{ item.value }}"
      loop: "{{ my_ami_list | dict2items }}"
